[application]
name = "cyclcalc"

[web.app]
title = "Форма Dioxus"

[bundle]
identifier = "ru.cyclcalc.desktop"
publisher = "cyclcalc"
short_description = "Простое desktop-приложение на Dioxus"
category = "Utility"
